using ClosedXML.Excel;
using Microsoft.JSInterop;
using Radzen;
using System.Data;
using System.Text;
using TelephonyUI.Models;
using TelephonyUI.Models.CallCenterModels;
using TelephonyUI.Services.Interfaces;

namespace TelephonyUI.Services
{
	public class DataExportService : IDataExportService
	{
		private readonly IJSRuntime _jsRuntime;

		public DataExportService(IJSRuntime jsRuntime)
		{
			_jsRuntime = jsRuntime;
		}

		public async Task ExportToExcel(IEnumerable<Call> data)
		{

			// Offload DataTable creation and Excel processing to a background thread
			var dataTable = await Task.Run(() =>
			{
				var dt = new DataTable("Calls");
				dt.Columns.AddRange(new DataColumn[]
					{
					new DataColumn("Agent Name"),
					new DataColumn("Agent Number"),
					new DataColumn("Call Time"),
					new DataColumn("Customer Type"),
					new DataColumn("Account Number"),
					new DataColumn("Call Duration"),
					new DataColumn("Caller Number")
						// Other columns ...
					});

				foreach (var call in data)
				{
					dt.Rows.Add(
						call.Agent != null ? $"{call.Agent.FirstName} {call.Agent.LastName}" : "N/A",
						call.Agent?.Extension,
						call.StartTime.ToString("g"),
						call.Customer?.Type.ToString() ?? "N/A",
						call.Customer?.AccountNumber ?? "N/A",
						call.TalkTime.ToString(@"mm\:ss"),
						call.CallerNumber
					// Other rows ...
					);
				}
				return dt;
			});


			// Create Excel workbook
			using (var workbook = new XLWorkbook())
			{
				var worksheet = workbook.AddWorksheet(dataTable, "Call History");
				// Format columns
				worksheet.Columns().AdjustToContents();


				// Add footer
				worksheet.PageSetup.Margins.Bottom = 1.5; // Increase bottom margin
				worksheet.PageSetup.Margins.Footer = 0.5; // Space between footer and page bottom
				worksheet.PageSetup.Footer.Center.AddText($"Exported on {DateTime.Now:g}");
				worksheet.PageSetup.Footer.Left.AddText("Generated by Admin");
				worksheet.PageSetup.Footer.Right.AddText("Page &P of &N");

				// Optional: Fit data to page width
				worksheet.PageSetup.PageOrientation = XLPageOrientation.Landscape;
				worksheet.PageSetup.FitToPages(1, 0); // 1 page wide

				// Save to memory stream
				using (var stream = new MemoryStream())
				{
					workbook.SaveAs(stream);
					var content = stream.ToArray();

					// Trigger download
					var fileName = $"CallHistory_{DateTime.Now:yyyyMMddHHmmss}.xlsx";
					await _jsRuntime.InvokeVoidAsync("downloadExcel",
						fileName,
						Convert.ToBase64String(content));
				}
			}


		}

		//-------------------//

		public async Task ExportToFormattedCsv(IEnumerable<Call> data)
		{
			// Generate CSV content
			var csvContent = GenerateFormattedCsv(data);

			// Create Blob and download
			var fileName = $"CallHistory_Formatted_{DateTime.Now:yyyyMMddHHmmss}.csv";
			await _jsRuntime.InvokeVoidAsync("downloadFormattedCsv", fileName, csvContent);
		}

		private string GenerateFormattedCsv(IEnumerable<Call> data)
		{
			var csv = new StringBuilder();

			// Add UTF-8 BOM
			csv.Append('\ufeff');

			// Headers
			csv.AppendLine("Agent First Name,Agent Last Name,Agent Extension,Call Start Time,Call End Time,Caller Number,Customer Type,Call Duration (s),Notes");

			foreach (var call in data)
			{
				var fields = new[]
				{
				EscapeFormattedCsv(call.Agent?.FirstName),
				EscapeFormattedCsv(call.Agent?.LastName),
				EscapeFormattedCsv(call.Agent?.Extension),
				call.StartTime.ToString("o"),
				call.EndTime?.ToString("o") ?? "",
				EscapeFormattedCsv(call.CallerNumber),
				EscapeFormattedCsv(call.Customer?.Type.ToString()),
				call.TalkTime.TotalSeconds.ToString("0"),
				EscapeFormattedCsv(call.Notes)
			};

				csv.AppendLine(string.Join(",", fields));
			}

			return csv.ToString();
		}

		private string EscapeFormattedCsv(string value)
		{
			if (string.IsNullOrWhiteSpace(value)) return "";

			// Escape quotes and handle newlines
			value = value.Replace("\"", "\"\"");

			if (value.Contains(",") || value.Contains("\"") || value.Contains("\r") || value.Contains("\n"))
			{
				return $"\"{value}\"";
			}
			return value;
		}

		//-------------------//

		public async Task ExportToPDF(IEnumerable<Call> data, bool isLandscape)
		{
			// Get current user/app name (replace with actual value)
			var generatedBy = "Admin";
			// Or get from authentication: await AuthService.GetUserName();

			await _jsRuntime.InvokeVoidAsync(
			"exportToPDF",
			GetExportData(data),
			isLandscape,
			generatedBy // Pass generatedBy parameter
		);

		}

		private List<ExportRecord> GetExportData(IEnumerable<Call> calls)
		{
			return (calls)
				.Select(call => new ExportRecord
				{
					agentName = $"{call.Agent?.FirstName} {call.Agent?.LastName}".Trim(),
					agentNumber = call.Agent?.Extension ?? "N/A",
					callTime = call.StartTime.ToString("yyyy-MM-dd HH:mm"),
					customerType = call.Customer?.Type.ToString() ?? "N/A",
					accountNumber = call.Customer?.AccountNumber ?? "N/A",
					callDurationSeconds = (int)(call.TalkTime.TotalSeconds),
					callerNumber = call.CallerNumber ?? "N/A"
				})
				.ToList();
		}

		private class ExportRecord
		{
			// Match JavaScript property names exactly
			public string agentName { get; set; }
			public string agentNumber { get; set; }
			public string callTime { get; set; }
			public string customerType { get; set; }
			public string accountNumber { get; set; }
			public int callDurationSeconds { get; set; }
			public string callerNumber { get; set; }
		}

	}
}
